name: mat282
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=7.5
  - jupyterlab=2.1.3
  - matplotlib-base=3.2
  - numpy
  - pandas=1
  - pandas-profiling
  - pip
  - pillow
  - python=3.7
  - scipy
  - scikit-image
  - scikit-learn=0.23
  - altair=4
  - altair_saver